### PR TITLE
New-style settings and three finger drag

### PR DESCRIPTION
**Pull request by usr-sse2**
These commits introduce the following improvements for Synaptics touchpad driver:
1. Support for new-style (animated) Trackpad preference pane. This works on macOS Sierra and doesn't need ioio.
2. Three-finger drag, like on MacBooks.
3. Improved debug logging: use named touchmodes instead of numeric values
4. Left and right click corners can be swapped for left-handed users convenience.

Trackpad options can be configured there:

- secondary click (all values)
- tap to click
- tracking speed

- swipe between full-screen apps (only three fingers, simulates ctrl-arrow)
- mission control and app exposé (only three fingers, simulates ctrl-arrow)

- double-click speed
- scrolling speed
- scrolling (all values)
- dragging (all values)

Some gestures are made mutual-exclusive or dependent by Apple, for example, enabling three-finger drag disables three-finger swipes and vice versa, and one-finger dragging requires tapping and thus enables it.

### CODE REVIEW

**Comment by usr-sse2** [comment]
Note that although three-finger dragging is usable, it still has some minor issues (e. g. rare 'jumps' when finger count changes from 1 or 2 to 3 during the touch, or inability to complete dragging without waiting for the timer).

**Comment by the-braveknight** [comment]
Wow that looks nice! Finally a solution for the trackpad PrefPane. I just wish it supported my ELAN trackpad... :(

**Comment by ilyamodder** [comment]
It does not work properly on El Capitan: the trackpad recognizes as a mouse, and trackpad preference pane says "no bluetooth trackpads found".

**Comment by usr-sse2** [comment]
@ilyamodder, try manually kextloading VoodooPS2Trackpad.kext. If it works, try rebuilding the kernelcache.
I tested on an old machine with Snow Leopard and it works as a trackpad (Snow Leopard didn't have the animated prefpane with new gestures, so it just continued working without any changes).
I'll install El Capitan and check on it.

**Comment by usr-sse2** [comment]
@ilyamodder, I figured out that for Snow Leopard the new way of detecting multitouch trackpad (via ApplePreferenceIdentifier property in ioreg) doesn't work, so I got it to work by setting the class of the driver to AppleUSBMultitouchDriver. Originally I used this idea on Sierra, but switched to ApplePreferenceIdentifier because we can't make 3 classes with the same name in one kext (for Synaptics, ALPS and Sentellic).

**Comment by usr-sse2** [comment]
@ilyamodder, try this variant (f88976f)

**Comment by ilyamodder** [comment]
@user-sse2, thanks! I'll try it later.

**Comment by ilyamodder** [comment]
No changes between old and new versions.

**Comment by usr-sse2** [comment]
Ok, I'm already downloading El Capitan.

**Comment by tluck** [comment]
Excellent work. I tested implemented on my Lenovo T420 and T460 (which has code mods for its 3 physical buttons). 

a question: does the scrolling in Safari or Chrome move images/content smoothly in Sierra? In Sierra the scrolling in Safari is more like a wheel mouse scroll - bigger jumps - like a line at a time versus a few pixels. I have a apple magic mouse and In El Cap the TrackPad and ClickPad scrolling is very similar. but in Sierra it is very jittery.  Thoughts or suggestions?

**Comment by usr-sse2** [comment]
@ilyamodder, I've installed El Capitan and it just works, even without the latest commit. What does kextstat show? Did you try manually kextloading VoodooPS2Trackpad?
screen shot 2016-11-03 at 12 06 11

**Comment by jakibaki** [comment]
@tluck sorry for going of topic but can you upload your modded kexts with this patch?

A friend of mine has an x240 (with the x260 touchpad) and I have an x220.

**Comment by the-braveknight** [comment]
I would really love to use this kext for my ELAN trackpad instead of ApplePS2SmartTouchPad.kext which is very buggy and unreliable... Is it not possible for you to implement ELAN support in VoodooPS2?

**Comment by usr-sse2** [comment]
The author of AppleSmartElanTouchpad spent years developing his driver. How do you expect me to make something better than that in a couple of days, without even having the hardware? VoodooPS2Trackpad is actually three separate drivers - for Synaptics, Sentellic and ALPS. It's not a generic framework to add different device support to.

**Comment by the-braveknight** [comment]
I understand... Especially when the ELAN kext author has not released the source code... :(

**Comment by tluck** [comment]
@jakibaki - see the zip here for the revised compiled kext - i will update my github repo with the mods. i basically pulled this repo down and added some logic to handle 3 real buttons (TrackPoint):    http://www.insanelymac.com/forum/topic/285678-lenovo-thinkpad-t420-with-uefi-only/page-25#entry1952283

@usr-see2 - i am wondering why i don't see the 3 finger drag option in Accessibility/Mouse & Trackpad options. under Enable dragging - i get "with/without drag lock" in the pull down?

**Comment by usr-sse2** [comment]
@tluck, what's the value of TrackpadThreeFingerDrag property of AppleUSBMultitouchDriver or ApplePS2SynapticsTouchPad in your ioreg? If you can't see this option, this is probably false. Don't know who sets it to false.
Here https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/pull/90/files#diff-139154da8e372a3c25a75bbfe0197629R1519 a line that sets its value is specially commented out, so it would remain its value from the plist.

**Comment by tluck** [comment]
Ok thanks. probably little value!

i  like the drag/draglock feature currently in play for my Lenovo Trackpad/Clickpads. I was wondering if i was missing something as the drag option was different. so just looking for validation etc. that plus,  the vertical scroll in sierra safari is  jumpy (acts like wheel scroll) - so thought maybe something wasn't set right?

**Comment by jakibaki** [comment]
@tluck: thanks!

**Comment by usr-sse2** [comment]
@tluck, Here was a long comment about the jumpy scrolling, but Safari Technology Preview crashed before I posted it :( Will rewrite it later.

**Comment by tluck** [comment]
well interesting... just installed 10.12.2 beta and scrolling is very smooth in safari. 
i set TrackpadThreeFingerDrag true in info.plist - and i get the option now in Accessibility menu. doesn't seem to work i.e. drag anything - but i frankly like click/drag anyway. 
great work on this. thanks again.  i have merged in my ClickPad mods and it is working great on both T420 and T460.

**Comment by usr-sse2** [comment]
@tluck,
1. it's strange that three-finger drag doesn't work, I have both Lenovo (but buttonless) and non-Lenovo notebooks with Synaptics touchpads and it works on them. do three-finger swipes work for you? (if enabled in System Preferences and set to three fingers)
2. why was TrackpadThreeFingerDrag false in your Info.plist? is it because of your commits for the third button?
3. compile a debug version and post a log of what's happening when trying to drag with three fingers:
`log stream --predicate 'processID == 0'`

**Comment by usr-sse2** [comment]
A note about jumpy scrolling: I investigated this problem and discovered that true Momentum scrolling devices send Momentum events:
`2016-11-06 20:57:28.318699 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114562.4 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=0.000000 deltaY=-1.000000 count:0 phase=Began momentumPhase=None
2016-11-06 20:57:28.331080 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114562.4 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=4.000000 deltaY=-21.000000 count:0 phase=Changed momentumPhase=None
2016-11-06 20:57:28.342634 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114562.4 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=1.000000 deltaY=-7.000000 count:0 phase=Ended momentumPhase=None
2016-11-06 20:57:28.352811 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114562.4 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=1.000000 deltaY=-7.000000 count:0 phase=None momentumPhase=Began
2016-11-06 20:57:28.364110 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114562.5 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=1.000000 deltaY=-7.000000 count:0 phase=None momentumPhase=Changed
<many Changed events with decreasing |deltaY|>
2016-11-06 20:57:29.078536 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114563.2 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=0.000000 deltaY=-1.000000 count:0 phase=None momentumPhase=Changed
2016-11-06 20:57:29.090233 events[32201:1264385] NSEvent: type=ScrollWheel loc=(383,143) time=114563.2 flags=0x100 win=0x6000001e0600 winNum=13260 ctxt=0x0 deltaX=0.000000 deltaY=0.000000 count:0 phase=None momentumPhase=Ended`
However, VoodooPS2Trackpad sends all events with phase=None momentumPhase=None (just discrete scrolls). I tried to modify event subtype using a private setScrollType method of IOHIPointing but I did something wrong because the IOLog in my code wasn't called.

**Comment by usr-sse2** [comment]
c23bc4f Fixed scrolling on Sierra. A simple change to Info.plist has done the thing, with no hacking with private methods.

**Comment by tluck** [comment]
Very nice indeed. These new scroll settings work on the Lenovo T420 and T460 - very smooth scrolling for Safari.

getting back to ThreeFingerDrag. 

I would not think that this issue has anything to do with the T460 clickPad button implementation - this is a simple fix to read the 3 TrackPoint Buttons - which are implemented in a different manor as compared to the T420 with its 2 sets of buttons. 
see this file for fairly simple changes to read the left/middle/right buttons vs clickPad edge. 
https://github.com/tluck/OS-X-Voodoo-PS2-Controller/blob/master/clickpad-patch.txt

So when i turn on (set true) TrackpadThreeFingerDrag in the Info.plist, I get the option to set Drag using 3 fingers  in Accessibility/TrackPad - however trying to use it - dragging this way doesn't seem to work.  Where as the "click/drag with/without drag lock"  works fine.
3 finger swipe left/right (back/forward) works fine.

It seems when 3 finger drag is enabled there is some conflict with these other features -  dragging ceases to work. Since personally I prefer click/drag - I have not pursued investigating. 

thanks again!

**Comment by usr-sse2** [comment]
Removed unnecessary changes to plists (key reordering) by rewriting history.
Added a strange workaround for Caps Lock problem, but haven't tested on previous OS X versions. It works bad when two keyboards (PS/2 and USB) are used together.

**Comment by vaslobas** [comment]
@usr-sse2 Can u please share compiled version of ur kext? Thanks!

**Comment by x4080** [comment]
@usr-sse2, I'm interested in the kext also, or how to combine your commit to the original source quickly? Or you can share your mod source? Or the kext will be fine

Thanks

**Comment by x4080** [comment]
@usr-sse2 I wondered if 4 fingers gesture is working? I think about using 4fingers to do run launchpad?

**Comment by x4080** [comment]
@tluck , I'm using your kext and works fine, then I tried to compile my self the code from @usr-sse2, and the one that I compile myself cannot work (keyboard and trackpad is not detecting types/touches), is there anything else that I have to change? I'm using synaptics trackpad (xps 9350)

Thanks

**Comment by x4080** [comment]
Never mind, solve it with target as all

**Comment by RehabMan** [comment]
Thanks for submitting, but I will not pull these changes (too many gratuitous changes).
I have cherry picked a few changes and implemented other fixes for v1.8.25.
I will continue to watch the usr-sse2 fork for anything interesting.

**Comment by matrixbud** [comment]
I have the Caps-Lock bug in Sierra 10.12.4 using a Microsoft Wireless Comfort Keyboard 5000.  That is, it requires 2 taps to change back and forth between regular and caps lock. Is there any fix for this?

**Comment by RehabMan** [comment]
Maybe you should reproduce the problem on a real Mac, then report the bug to Apple.
I did a workaround in my PS2 keyboard driver, but that won't help you with what is essentially a USB keyboard.

**Pull request closed without merging**
