### PR TITLE
Glide point

### PR DESCRIPTION
**Pull request by jief666**
Hi Rehabman.

I made few change to make my M4300 (and I suppose D6xx D8xx as weel) work.
There was a bug in ApplePS2ALPSGlidePoint::packetReady() that could make a panic (see line _ringBuffer.advanceTail(kPacketLengthSmall)).
In Synaptics, except a small thing (check if device is disabled) and some debug_log, I didn't touch.

Would you like to integrate my changes in your main branch ?

Regards.
Jief

### CODE REVIEW

**Comment by RehabMan** [comment]
Too many unrelated changes as compared to the one bug you'd like fixed.
Submit a clean pull, and I'll consider.

**Comment by jief666** [comment]
Sorry, it's a year old. Don't have time to put my head in that again.
Take only the changes you want, that's fine by me.

**Comment by RehabMan** [comment]
Problem is I see a potential bug in the packetReady function, but I don't see that you made any changes there...

**Comment by RehabMan** [comment]
Closing. Fix to buffering issue is already in the repo.

**Pull request closed without merging**
