### PR TITLE
Add in Trackpoint support for Thinkpads

### PR DESCRIPTION
**Pull request by jcsnider**
I did my best to pull out the bare minimum from @tluck's repo in order to add trackpoint support into this original repo.  I'm hoping that you'll accept these changes (or work with me to adjust into an acceptable state).

There are several components that I will try to discuss.

First is adding flags/info.plist values to that can be used to determine if a full hardware reset is required on start, and whether or not the machine is a thinkpad.

The second commit modifies the variables of the first slightly and adds all of the logic required for the three physical trackpoint buttons to operate.  There is some extra logic scattered around to break out of functions if we are using the middle mouse button to drag content.  If the "isthinkpad" variable is false then there should be absolutely no difference in how this acts for everyone else.

The final commit is just adding values to the info.plist file for different Thinkpad models.  These can be expanded upon but it allows us to specify that we are using a lenovo thinkpad and the kext will load everything else and act appropriately.

I'm happy to answer any and all questions regarding these changes... I tried to keep comments in there to explain why some blocks of code are necessary.  I'd very much like to get these changes merged into your master branch because I know you will continue improving upon this extension whilest I cannot say the same about myself or tluck in the future.

I am making a post now on tonymac to have Cobra and Sinki test my kext and make sure it works for them out of the box.
Link: https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-t440s.244798/page-4#post-1730154

I'm also attaching a compiled kext so it can be tested (if you'd like) on a non Thinkpad machine.
[jcsnider-VoodooPS2Controller.kext.zip](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/files/1911612/jcsnider-VoodooPS2Controller.kext.zip)

Thanks,
JC

### CODE REVIEW

**Comment by CoBrA2168** [comment]
I can confirm the compiled kext provided by jcsnider is working great with my Lenovo T440s (with the upgraded 3-button trackpad + trackpoint) on macOS Sierra 10.12.6.

**Comment by winterland1989** [comment]
I can confirm the compiled kext is working on my W540, but i have a problem with default sensitivity,  the trackpoint is moving too fast comparing to my touchpad, can it be adjust with some info.plist modification? @jcsnider

**Comment by jcsnider** [comment]
@winterland1989 because you didn't mention the buttons not working, have you modified your DSDT/SSDTs PS2K to return a oem-id and  oem-table-id?

[See here for an example](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/SSDT-KEY-DELL-WN09.dsl).. knowing if you have done something similar and if so what values you've used will be helpful in instructing you how to proceed.

**Comment by jcsnider** [comment]
@RehabMan any thoughts/ideas/concerns on this? Would love to get this merged in.

**Comment by RehabMan** [comment]
I'll let you know after I have time to look at the details...

**Comment by RehabMan** [comment]
That first commit for the "LENOVO" PlatformProfile data seems a bit fishy.
My suggestion would be to do all overrides with SSDT, not Info.plist changes.
And most of those settings are not read in the code anyway...

I'll merge it, then probably undo that entire commit, transferring only the settings that are actually handled in the resulting code into an SSDT.

**Comment by jcsnider** [comment]
That's fine. I pulled almost all of that directly from tLucks fork without scrutiny. I didn't want anyone using his kext to switch and have problems -- if any of those values don't matter/wouldn't work then let's remove them. I'd actually be happier with overriding everything via SSDT. With how easy hot patching is these days users would have better control over the sensitivities of the nub and such.

**Comment by tluck** [comment]
Cool. I look forward to testing it on my T420 -- and perhaps (hopefully) my version will obsolete! 
I don't have a T460 to test the clickpad side but maybe others can test it out with the new SSDT etc.

**Comment by tluck** [comment]
Thanks JC and RehabMan for pulling this together. I have updated the T420 and T460 guides with this kext and appropriate SSDT for PS2K.

**Comment by CoBrA2168** [comment]
@tluck - can you share the link to that guide here? I'm on a T440s (with the upgraded 3 button trackpad) so I'm assuming the T460 files would work for my configuration.

**Comment by tluck** [comment]
@CoBrA2168 - you get all the files on github.com/tluck

**Comment by tluck** [comment]
@CoBrA2168  - curious does the new stuff work ok for you?

**Comment by CoBrA2168** [comment]
@tluck - haven't had a chance to try it yet.  I'm using the kext that @jcsnider built before the pull and it's working flawlessly.

I believe the SSDT for keyboard is needed to make everything work correctly.  Is it working for you?

**Comment by jcsnider** [comment]
This is still working great for me. I finally got my X1 guide out :)

Thanks again, @RehabMan -- I'm deleting my fork of VoodooPS2Controller now.

**Comment by tluck** [comment]
metoo - the only thing i needed to change on the T420 is bogusDeltaThresh otherwise the trackpad is very jumping/laggy. with overrides in the SSDT files - much easier to customize - not having to mess with separate kext mods etc.

Great to have the Lenovo ThinkPad support in the master branch. anyway, works fantastic.  thanks.

**Comment by RehabMan** [comment]
Currently only the T420 maps to Thinkpad_Trackpad in the Info.plist.
BogusDeltaThreshX/Y are set to 100 there.
Maybe they should be changed to the values that you're using?

**Comment by tluck** [comment]
that's seems like a good idea. oddly 100 wasnt enough - so I used 800 ... but didn't dicker with this much to find the "edge"

**Comment by RehabMan** [comment]
I'll wait for someone to experiment with it to find the edge...
(I don't want to make the change more than once).

**Pull request merged**
