### PR TITLE
alps v6 protocol (dell n5110)

### PR DESCRIPTION
**Pull request by radut**
alps v6 protocol (dell n5110)

tilda(`~|) fix for dell N5110 WN09

### CODE REVIEW

**Comment by RehabMan** [comment]
There are still commits to the Synaptics code.  If this is specific to ALPS, please remove all changes related to Synaptics. 

Perhaps you should start over... and keep this commit clean and related only to ALPS.

**Comment by cprovatas** [comment]
Was there ever any success getting the ALPS trackpad working in this branch?  I see the pull request is still open.  I have a Lenovo Y50 with the ALPS trackpad and this looks like the closest thing that I can find to get this working w/ multitouch on OSX.. 

Thank you

**Comment by RehabMan** [comment]
Try radut's fork.  I have no hardware to test with, and this pull was never granted due to changes to the Synaptics code (eg. the pull is not very clean).  I didn't want to risk messing with the Synaptics stuff.

**Comment by cprovatas** [comment]
Will do thank you

**Comment by RehabMan** [comment]
Will not pull (PR is not clean).  Closing.

**Pull request closed without merging**
